config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: [:new, :show, :create, :destroy], shallow: true do
    resources :bookmarks, only: [:create, :destroy]
  end
  #resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
  
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
 
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
 

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      @movies = Movie.all.order(:title)
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all.order(:title)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <div class="container">
    
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag "image2navBar.jpeg", alt: "popicor", width: 200 %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">My Lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">New List</a>
          </li>
          <li class="nav-item dropdown">
            <!--<img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />-->
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <li class="nav-item">
          </li>
      </ul>
    </div>
  </div>
</div>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container pt-5">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <p><%= list.name %></p>
    <% end %>
  <% end %>
  <%= link_to 'crie uma lista', new_list_path %>
</div>

app/views/lists/new.html.erb
<div class="container pt-5">
  <%= simple_form_for @list do |f| %>
    
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>

  <%= link_to 'voltar', root_path %>
</div>

app/views/lists/show.html.erb
<div class="container pt-5">
  <h2><%= @list.name %></h2>
   <%= link_to 'Delete a lista', list_path(@list), method: :delete %>
  <hr>
  <h3>Movies</h3>

  <% @list.bookmarks.each do |bookmark| %>
    <div class="container">
      <div class="row">
        <div class="col-6">
          <%= image_tag bookmark.movie.poster_url, width: 300 %>
        </div>
        <div class="col-6">
          <p><%= bookmark.movie.title %></p>
          <p><%= bookmark.movie.overview %></p>
          
          <p><%= bookmark.comment %></p>
        </div>
      </div>
      
      <%= link_to 'Delete a Bookmark', bookmark_path(bookmark), method: :delete %>
      <hr>
    </div>
  <% end %>
  

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: @movies, prompt: "Choose a Movie", label: false %>
    <%= f.input :comment, placeholder: "Take a Comment", label: false %>
    <%= f.submit %>
  <% end %>
  <hr>
  <%= link_to 'Voltar', root_path %>
</div>